results:
  title: "Report for Basic Snakemake Workflow"
  path: results_report/
  # create self contained file (TODO)
  embedded: False
  # if description template is not specified, the template from the snakefile (report directive) is used 
  description: report_template/workflow_overview.md 
  # here you can explicitly define the order of sections, and additional templates
  result_sections:
    "sample1":
      skip: True
    "Data Generation": 
      #skip: True # this section will be skipped (with all result files in it)
      template: report_template/data_generation.md
      table: my_specific_table
      subsections:
        Other:
          template: report_template/data_generation_subsection.md
    "Data Visualization":
      template: report_template/data_visualization.md
      image: large
    Aggregation: 
      # default rendering 
      # - header, no text, all result files are concatenated 
    # Categories not listed here are added with default 
    # rendering in alphabetical order
    # to skip a category add:
    # Category_name: skip
    # "[...]": 
    #   template: default
    # References:
    #  template: report_template/references

  # specify default rendering options for    
  render_options: 
    image:
      suffix:
        - "jpg"
        - "png"
      width: 512
      link: False
      presets:
        large:
          width: 1024
    table:
      suffix:
        - "csv"
        - "tsv"
      sep:
        default: "\t"
        csv: ","
      max_row: 10 # fist n rows only
      index: False 
      numalign: "right"
      stralign: "center"
      missingval: "N/A"
      link: False
      presets:
        show_100:
          max_row: 100
        my_specific_table: 
          max_row: 5
          col_select: [0,1] # select a subset of columns
          headers: ["index", "value"] # overwrite column headers
          floatfmt: ".1f"

      
resources:
  path: resource_report.html